version: '3.0'

services:
  server:
    image: winnden/server
    container_name: server
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always
  postgres:
    image: winnden/postgres:latest
    container_name: postgres
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: