version: '3.0'

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  main:
    image: winnden/server
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7000:7000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  

volumes:
  pgdata: