version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build:
      dockerfile: db/Dockerfile
      context: .
    ports:
      - "5432:5432"
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    
  main:
    image: winnden/server
    build: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7000:7000
      - 9229:9229
    command: npm run start:prod
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:

networks:
  docker-network:
    driver: bridge