name: CI

on:
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just'
          
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Login to server
        run: ssh root@${{ secrets.SSH_HOST }} exit
        
      - name: Build Docker image
        run: docker compose build
      - name: Show containers
        run: docker ps -a
      - name: Show images
        run: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Server image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/server;
      - name: Deploy to server
        run: >
          ssh -T root@${{ secrets.SSH_HOST }} "
          git clone https://github.com/Polyakov-itmo/Practice
          docker-compose up
          exit
          "
