name: CI

on:
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just'
          
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Login to server
        run: ssh root@${{ secrets.SSH_HOST }} exit
        
      - name: Build Docker image
        run: docker compose build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Server image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/server;
      - name: Push Postgres image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/postgres;
      - name: Deploy to server
        run: >
          ssh -T root@${{ secrets.SSH_HOST }} "
          docker ps -aq | xargs docker stop | xargs docker rm;
          docker stop $(docker ps -a -q);
          docker pull ${{ secrets.DOCKER_USERNAME }}/server;
          docker pull ${{ secrets.DOCKER_USERNAME }}/postgres;
          docker run -d ${{ secrets.DOCKER_USERNAME }}/server:latest;
          docker run -d ${{ secrets.DOCKER_USERNAME }}/postgres:latest;
          exit
          "
