name: CI

on:
  push:
    branches: [ "master" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install SSH key
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: 'not_empty'
     - name: Login to server
       run: ssh -T root@${{ secrets.SSH_PRIVATE_HOST }} exit
     - name: Build Docker image
       run: docker compose build
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
       
